--------------------------------------------------------
--  DDL for Table FLOOD_DETECTION
--------------------------------------------------------

  CREATE TABLE "SMARTPARKING"."FLOOD_DETECTION" 
   (	"ROW_ID" NUMBER, 
	"CURRENT_LEVEL" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRECISE_COUNTER" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
