--------------------------------------------------------
--  DDL for Table FLOOD_DETECTION
--------------------------------------------------------

  CREATE TABLE "GSMUSER"."FLOOD_DETECTION" 
   (	"ROW_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CURRENT_LEVEL" VARCHAR2(20 BYTE), 
	"PRECISE_COUNTER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FLOOD_DETECTION
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."FLOOD_DETECTION" MODIFY ("ROW_ID" NOT NULL ENABLE);
